apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoml-deployment
spec:
  selector:
    matchLabels:
      app: demoml
  replicas: 3
  template:
    metadata:
      labels:
        app: demoml
    spec:
      containers:
      - name: demoml
    # enter the path to your image, be sure to include the correct region prefix    
        image: bom.ocir.io/bmcuwjfoonzp/demomlrepo/demoml:v2
        ports:
        - containerPort: 5000
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: mlsecret3
---
apiVersion: v1
kind: Service
metadata:
  name: demoml-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: demoml